### ISSUE TITLE
IE 10

### ISSUE THREAD

**Issue by SarahTierney** [Mjams/dsn1675-project-1#5]
The browser puts a blue border around the social media icons, so in your css images tag write " border: 0; ".
<img width="420" alt="screen shot 2015-10-09 at 1 06 11 pm" src="https://cloud.githubusercontent.com/assets/10464614/10400451/d22e5c12-6e86-11e5-8690-3f06d3d0570c.png">

**Comment by Mjams** [comment]
No more Borders, and issues with IE fixed, Thanks
