### ISSUE TITLE
CSS validation errors

### ISSUE THREAD

**Issue by Lenzo** [Mjams/dsn1675-project-1#6]
Hello, 

I think Thomas said the error on line 244 is ok. but it looks like you have an extra bracket within your last media query
![screen shot 2015-10-09 at 1 15 42 pm](https://cloud.githubusercontent.com/assets/10464664/10400632/dbac0608-6e87-11e5-9def-633b68074c8d.png)

**Comment by Mjams** [comment]
fixed it, that bracket is the closing bracket for the print media query, thanks!
